/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GlossaryTerm = IDL.Record({
  'term' : IDL.Text,
  'definition' : IDL.Text,
});
export const Difficulty = IDL.Variant({
  'Beginner' : IDL.Null,
  'Advanced' : IDL.Null,
  'Intermediate' : IDL.Null,
});
export const Question = IDL.Record({
  'question' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Lesson = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
export const Module = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'difficulty' : Difficulty,
  'quiz' : IDL.Vec(Question),
  'description' : IDL.Text,
  'lessons' : IDL.Vec(Lesson),
});
export const QuizResult = IDL.Record({
  'score' : IDL.Nat,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getGlossary' : IDL.Func([], [IDL.Vec(GlossaryTerm)], ['query']),
  'getGlossaryTerm' : IDL.Func([IDL.Text], [GlossaryTerm], ['query']),
  'getModuleById' : IDL.Func([IDL.Nat], [Module], ['query']),
  'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
  'getQuizQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
  'getUserProgress' : IDL.Func(
      [],
      [
        IDL.Record({
          'completedModules' : IDL.Vec(IDL.Nat),
          'quizResults' : IDL.Vec(IDL.Tuple(IDL.Nat, QuizResult)),
        }),
      ],
      ['query'],
    ),
  'markModuleCompleted' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'submitQuiz' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [
        IDL.Record({
          'score' : IDL.Nat,
          'totalQuestions' : IDL.Nat,
          'percentage' : IDL.Nat,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GlossaryTerm = IDL.Record({
    'term' : IDL.Text,
    'definition' : IDL.Text,
  });
  const Difficulty = IDL.Variant({
    'Beginner' : IDL.Null,
    'Advanced' : IDL.Null,
    'Intermediate' : IDL.Null,
  });
  const Question = IDL.Record({
    'question' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Lesson = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const Module = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'difficulty' : Difficulty,
    'quiz' : IDL.Vec(Question),
    'description' : IDL.Text,
    'lessons' : IDL.Vec(Lesson),
  });
  const QuizResult = IDL.Record({ 'score' : IDL.Nat, 'timestamp' : IDL.Int });
  
  return IDL.Service({
    'getGlossary' : IDL.Func([], [IDL.Vec(GlossaryTerm)], ['query']),
    'getGlossaryTerm' : IDL.Func([IDL.Text], [GlossaryTerm], ['query']),
    'getModuleById' : IDL.Func([IDL.Nat], [Module], ['query']),
    'getModules' : IDL.Func([], [IDL.Vec(Module)], ['query']),
    'getQuizQuestions' : IDL.Func([IDL.Nat], [IDL.Vec(Question)], ['query']),
    'getUserProgress' : IDL.Func(
        [],
        [
          IDL.Record({
            'completedModules' : IDL.Vec(IDL.Nat),
            'quizResults' : IDL.Vec(IDL.Tuple(IDL.Nat, QuizResult)),
          }),
        ],
        ['query'],
      ),
    'markModuleCompleted' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'submitQuiz' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [
          IDL.Record({
            'score' : IDL.Nat,
            'totalQuestions' : IDL.Nat,
            'percentage' : IDL.Nat,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };