/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Difficulty = { 'Beginner' : null } |
  { 'Advanced' : null } |
  { 'Intermediate' : null };
export interface GlossaryTerm { 'term' : string, 'definition' : string }
export interface Lesson { 'title' : string, 'content' : string }
export interface Module {
  'id' : bigint,
  'title' : string,
  'difficulty' : Difficulty,
  'quiz' : Array<Question>,
  'description' : string,
  'lessons' : Array<Lesson>,
}
export interface Question {
  'question' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export interface QuizResult { 'score' : bigint, 'timestamp' : bigint }
export interface _SERVICE {
  'getGlossary' : ActorMethod<[], Array<GlossaryTerm>>,
  'getGlossaryTerm' : ActorMethod<[string], GlossaryTerm>,
  'getModuleById' : ActorMethod<[bigint], Module>,
  'getModules' : ActorMethod<[], Array<Module>>,
  'getQuizQuestions' : ActorMethod<[bigint], Array<Question>>,
  'getUserProgress' : ActorMethod<
    [],
    {
      'completedModules' : Array<bigint>,
      'quizResults' : Array<[bigint, QuizResult]>,
    }
  >,
  'markModuleCompleted' : ActorMethod<[bigint], boolean>,
  'submitQuiz' : ActorMethod<
    [bigint, Array<bigint>],
    { 'score' : bigint, 'totalQuestions' : bigint, 'percentage' : bigint }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];