/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuizResult {
    score: bigint;
    timestamp: bigint;
}
export interface Question {
    question: string;
    correctAnswer: bigint;
    options: Array<string>;
}
export interface Lesson {
    title: string;
    content: string;
}
export interface Module {
    id: bigint;
    title: string;
    difficulty: Difficulty;
    quiz: Array<Question>;
    description: string;
    lessons: Array<Lesson>;
}
export interface GlossaryTerm {
    term: string;
    definition: string;
}
export enum Difficulty {
    Beginner = "Beginner",
    Advanced = "Advanced",
    Intermediate = "Intermediate"
}
export interface backendInterface {
    getGlossary(): Promise<Array<GlossaryTerm>>;
    getGlossaryTerm(term: string): Promise<GlossaryTerm>;
    getModuleById(id: bigint): Promise<Module>;
    getModules(): Promise<Array<Module>>;
    getQuizQuestions(moduleId: bigint): Promise<Array<Question>>;
    getUserProgress(): Promise<{
        completedModules: Array<bigint>;
        quizResults: Array<[bigint, QuizResult]>;
    }>;
    markModuleCompleted(moduleId: bigint): Promise<boolean>;
    submitQuiz(moduleId: bigint, answers: Array<bigint>): Promise<{
        score: bigint;
        totalQuestions: bigint;
        percentage: bigint;
    }>;
}
import type { Difficulty as _Difficulty, Lesson as _Lesson, Module as _Module, Question as _Question } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getGlossary(): Promise<Array<GlossaryTerm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlossary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlossary();
            return result;
        }
    }
    async getGlossaryTerm(arg0: string): Promise<GlossaryTerm> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlossaryTerm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlossaryTerm(arg0);
            return result;
        }
    }
    async getModuleById(arg0: bigint): Promise<Module> {
        if (this.processError) {
            try {
                const result = await this.actor.getModuleById(arg0);
                return from_candid_Module_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModuleById(arg0);
            return from_candid_Module_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getModules(): Promise<Array<Module>> {
        if (this.processError) {
            try {
                const result = await this.actor.getModules();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getModules();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuizQuestions(arg0: bigint): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuizQuestions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuizQuestions(arg0);
            return result;
        }
    }
    async getUserProgress(): Promise<{
        completedModules: Array<bigint>;
        quizResults: Array<[bigint, QuizResult]>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProgress();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProgress();
            return result;
        }
    }
    async markModuleCompleted(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markModuleCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markModuleCompleted(arg0);
            return result;
        }
    }
    async submitQuiz(arg0: bigint, arg1: Array<bigint>): Promise<{
        score: bigint;
        totalQuestions: bigint;
        percentage: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuiz(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuiz(arg0, arg1);
            return result;
        }
    }
}
function from_candid_Difficulty_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Module_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Module): Module {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    difficulty: _Difficulty;
    quiz: Array<_Question>;
    description: string;
    lessons: Array<_Lesson>;
}): {
    id: bigint;
    title: string;
    difficulty: Difficulty;
    quiz: Array<Question>;
    description: string;
    lessons: Array<Lesson>;
} {
    return {
        id: value.id,
        title: value.title,
        difficulty: from_candid_Difficulty_n3(_uploadFile, _downloadFile, value.difficulty),
        quiz: value.quiz,
        description: value.description,
        lessons: value.lessons
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Beginner: null;
} | {
    Advanced: null;
} | {
    Intermediate: null;
}): Difficulty {
    return "Beginner" in value ? Difficulty.Beginner : "Advanced" in value ? Difficulty.Advanced : "Intermediate" in value ? Difficulty.Intermediate : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Module>): Array<Module> {
    return value.map((x)=>from_candid_Module_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
